# Exercise Numpy

Jangan di-run all!. Lakukan run satu per satu pada tiap cell.

In [3]:
import numpy as np

<hr>

### **Nomor 1**

Buatlah sebuah array 1D dengan nama variable myArray yang terdiri dari 36 angka bilangan bulat acak antara 1 dan 100! (Gunakan seed=0)

In [37]:
np.random.seed(0)
myArrray = np.random.randint(1,100,36)
myArrray

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30])

<hr>

### **Nomor 2**

Ubahlah array tersebut (myArray) menjadi

* array 2D dengan ukuran 2 x 18
* array 2D dengan ukuran 9 x 4
* array 3D dengan ukuran 2 x 6 X 3

In [43]:
myArrray.reshape(2,18)
myArrray.reshape(9,4)
myArrray.reshape(2,6,3)

array([[[45, 48, 65],
        [68, 68, 10],
        [84, 22, 37],
        [88, 71, 89],
        [89, 13, 59],
        [66, 40, 88]],

       [[47, 89, 82],
        [38, 26, 78],
        [73, 10, 21],
        [81, 70, 80],
        [48, 65, 83],
        [89, 50, 30]]])

<hr>

### **Nomor 3**

Tentukan

* nilai minimum dari array tersebut (myArray)
* nilai maximum dari array tersebut (myArray)
* posisi dari nilai minimum tersebut
* posisi dari nilai maximum tersebut

In [59]:
display(np.min(myArrray))
display(np.max(myArrray))
display(np.where(myArrray == np.min(myArrray)))
display(np.where(myArrray == np.max(myArrray)))

10

89

(array([ 5, 25]),)

(array([11, 12, 19, 33]),)

<hr>

### **Nomor 4**

Buatlah array baru dengan nama variable new_array yang berisi 9 angka yang diambil dari data ke-3, 5, 30, 12, 15, 8, 24, 14, dan 22 dari myArray! 

Ubahlah array tersebut menjadi array 2D dengan ukuran 3 x 3 secara permanen!


In [76]:
new_array = myArrray[[3,5,30,12,15,8,24,14,22]]
new_array.reshape(3,3)

array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]])

<hr>

### **Nomor 5**

Tampilkan item pada new_array yang nilainya lebih besar dari 50!

In [78]:
np.extract(new_array > 50, new_array) #where to get the index, extract to get the value of the index

array([68, 89, 66, 73, 59])

<hr>

### **Nomor 6**

Buatlah sebuah array 1D yang berisi angka 0, 25, 50, 75, dan 100 menggunakan fungsi:

* arange
* linspace

In [83]:
display(np.arange(0,101,25))
display(np.linspace(0,100,5))

array([  0,  25,  50,  75, 100])

array([  0.,  25.,  50.,  75., 100.])

<hr>

### **Nomor 7**

Buatlah sebuah array 2D berukuran N X N yang semuanya berisi angka 8, dimana n merupakan bilangan asli yang besarnya dimintakan input kepada user!

contoh :\
N yang diinput adalah: 2

hasil :\
array([[8., 8.],\
&emsp;&emsp;&nbsp;&nbsp;&nbsp;[8., 8.]])

In [17]:
inputAngka = int(input("Please enter the array's dimension: "))
display(inputAngka)
temp = (np.ones((inputAngka,inputAngka)))
temp*8


3

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

<hr>

### **Nomor 8**

Buatlah array 2D dengan nama arrayA berukuran 3 x 4 dengan hasil sebagai berikut :

In [45]:
arr34 = np.arange(1,13)
arr34 = arr34.reshape(3,4)

Buatlah array 2D dengan nama arrayB berukuran 4 x 1 dengan hasil sebagai berikut :

In [46]:
arr41 = np.arange(100,401,100)
arr41 = arr41.reshape(4,1)

Gabungkanlah arrayA dan arrayB menjadi arrayC dengan hasil sebagai berikut:

In [48]:
arrayC = np.concatenate((arr34,arr41.T), axis=0) #axis 0 = baris, 1 kolom
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

<hr>

### **Nomor 9**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!

In [59]:
print(arrayC[1:3, 2:4]) #from row index-1,2, slice index-2,3

[[ 7  8]
 [11 12]]


<hr>

### **Nomor 10**

Tampilkan hasil sebagai berikut dengan cara melakukan slicing pada arrayC!

In [60]:
print(arrayC[3, 1])

200
