# NUMPY

In [8]:
import numpy as np
x = np.array([1, 2, 3])
np.mean(x)

2.0

In [9]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
display(np.random.rand(5,5))
display(np.random.randn(5,5))
display(np.random.randint(1,5,(3,3)))

array([[0.84902026, 0.59673075, 0.01440147, 0.00201604, 0.15044685],
       [0.71964454, 0.82250239, 0.90919018, 0.0117703 , 0.96674503],
       [0.66025457, 0.46645754, 0.11630395, 0.3873415 , 0.53318753],
       [0.77385471, 0.99175613, 0.4799764 , 0.94697068, 0.06420299],
       [0.89340645, 0.45979485, 0.53318484, 0.23454984, 0.15532238]])

array([[-0.26594347,  0.11458133,  1.12597444, -0.0891741 ,  0.26608384],
       [-0.31489245, -0.17016573, -1.02739915,  0.80621496, -0.903728  ],
       [ 0.65439093, -1.16075435, -0.60283228,  1.19035443, -1.42895648],
       [-0.95965998,  0.84382613, -0.40204586,  0.55367527, -0.51918518],
       [-0.39179281,  1.62609058, -1.48570975, -0.42631709,  0.28779545]])

array([[2, 1, 1],
       [2, 1, 3],
       [3, 2, 3]])

In [29]:
arr = np.arange(1,10)
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])