In [1]:
import numpy as np
import pandas as pd

## SOAL 1

a) Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input!


b) Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

In [13]:
arStart = 1 #int(input('Input start value: '))
arEnd = 28 #int(input('Input end value: '))

array = np.arange(arStart,arEnd)
display(array)

display(array.reshape(3,9))
display(array.reshape(3,3,3))
# array



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

## Soal 2
a) Buatlah sebuah array 1 dimensi dari data random integer sebanyak “n”, dimana “n” tersebut adalah sebuah input !

b) Batasan random juga ditentukan dalam input.

c) Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix!

d) Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan datanya!

Misalnya dari 1, 2, 3 menjadi 3, 2, 1.

In [112]:
n = 16 #int(input('Input value: '))
arStart = 1 # int(input('Input start value: '))
arEnd = 50 #int(input('Input end value: '))
array2 = np.random.randint(arStart,arEnd,n)
display(array2)
array2 = array2.reshape(4,4)
display(array2)
arr_sorted = np.array([sorted(row, reverse=True)[::-1] for row in array2])
arr_sorted


array([35, 23, 26, 11, 33, 33, 45, 48, 38,  2,  8,  8, 40,  6, 18, 38])

array([[35, 23, 26, 11],
       [33, 33, 45, 48],
       [38,  2,  8,  8],
       [40,  6, 18, 38]])

array([[11, 23, 26, 35],
       [33, 33, 45, 48],
       [ 2,  8,  8, 38],
       [ 6, 18, 38, 40]])

## SOAL 3

a) Buatlah sebuah array 2 dimensi dengan ukuran 10 x 10!

b) Isi dari array tersebut adalah:
1. Sisi luarnya merupakan angka 4.
2. Selain sisi luar, angka yang ditampilkan adalah 0.

In [4]:
base = np.zeros((8,8))
hor = np.ones((1,8))*4
ver = np.ones((10,1))*4
temp = np.concatenate((hor,base,hor), axis=0)
#temp
np.concatenate((ver,temp,ver), axis = 1)

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

## SOAL 4
a) Buatlah sebuah Series dengan menggunakan library Pandas!

b) Index pada Series tersebut berupa huruf lowercase dari a hingga z.

c) Data dari tiap indexnya adalah nomor dari 1 hingga 26.

In [5]:
label = 'a b c d e f g h i j k l m n o p q r s t u v w x y z'.split()
pd.Series(np.arange(1,27),index=label)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

## SOAL 5
a) Buatlah sebuah Series menggunakan angka random integer dari 1 hingga 5 sebanyak 100!

b) Hitunglah banyaknya frekuensi tiap angka!

c) Cari tahu 2 nilai dengan frekuensi tertinggi!

In [6]:
series5 = np.random.randint(1,5,100)
series5 = pd.value_counts(series5)
display(series5)
series5 = pd.DataFrame(series5.nlargest(2))
series5.reset_index().rename(columns={'index': 'value', 'count': 'frequency'})


4    31
1    29
2    24
3    16
Name: count, dtype: int64

value  frequency
0      4         31
1      1         29

## SOAL 6
a) Import library “seaborn”. Lalu, load data yang bernama “MPG”!

b) Tampilkan 5 data teratas pada DataFrame dari data “MPG”!

c) Tampilkan statistik deskriptif atau Describe data selain data numerik!

d) Tampilkan seluruh nama kolom pada DataFrame!

e) Hitung Jumlah Missing Value (data kosong) di setiap kolomnya!

In [7]:
import seaborn as sns
mpg = sns.load_dataset('MPG')
display(mpg.head(5))
display(mpg.describe(exclude='number'))
display(mpg.columns)
display(mpg.isna().sum())

mpg  cylinders  displacement  horsepower  weight  acceleration   
0  18.0          8         307.0       130.0    3504          12.0  \
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

## SOAL 7
a) Import library “seaborn”, lalu load data yang bernama “MPG”!

b) Tampilkan Missing value (data kosong) pada kolom ‘horsepower’!

c) Tampilkan index lokasi missing value tersebut!

In [8]:
display(mpg[mpg['horsepower'].isna()])
mpg[mpg['horsepower'].isna()].index

mpg  cylinders  displacement  horsepower  weight  acceleration   
32   25.0          4          98.0         NaN    2046          19.0  \
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

Index([32, 126, 330, 336, 354, 374], dtype='int64')

## SOAL 8
a) Import library “seaborn”, lalu load data yang bernama “MPG”!

b) Lakukan grouping atau pengelompokan berdasarkan kolom ‘origin’! Tampilkan
rata-rata dari ‘horsepower’ di setiap kelompok origin-nya!

In [9]:
mpg.groupby(['origin'])[['horsepower']].mean()

horsepower
origin            
europe   80.558824
japan    79.835443
usa     119.048980

## SOAL 9
a) Import library “seaborn”, lalu load data yang bernama “MPG”!

b) Buatlah sebuah kolom baru yang bernama ‘horse_origin’!

c) Kolom ‘horse_origin’ ini harus diisi menggunakan fungsi berisikan:

    ❑ Jika nilai ‘horsepower’ < 105, tampilkan ‘lower’ + ‘nama origin’ pada baris yang sama. Contohnya ‘lower USA’.
    
    ❑ Jika nilai ‘horsepower’ >= 105, tampilkan ‘upper’ + ‘nama origin’.

In [101]:
mpg = sns.load_dataset('MPG')
mpg['horse_origin'] = [(('upper ') + mpg['origin'][x]) if (x >= 105) else ('lower ') + mpg['origin'][x] if (x < 105) else '-' for x in mpg['horsepower']]
mpg


mpg  cylinders  displacement  horsepower  weight  acceleration   
0    18.0          8         307.0       130.0    3504          12.0  \
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite   upper japan  
3            70     usa              amc rebel sst   upper japan  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage   lower japan  
396          82     usa                ford ranger  lower europe  
397          82     usa                 chevy s-10   lower japan  

[398 rows x 10 columns]

## SOAL 10
a) Import library “seaborn”, lalu load data yang bernama “MPG”!

b) Lakukan pengelompokan atau grouping kolom ‘weight’ berdasarkan kolom
‘origin’ dengan aggregating mean, standart deviasi, sum, count, min, dan max!

c) Lakukan reset index sehingga kolom ‘origin’ tidak lagi menjadi index tapi tetap
menjadi kolom!

In [89]:
mpg = sns.load_dataset('mpg')

seriesSum = mpg.groupby('origin')[['weight']].sum()
seriesSum.reset_index(inplace=True)
seriesSum = seriesSum['weight']

mpg = mpg.groupby('origin')[['weight']].describe()
mpg = mpg['weight']
mpg.reset_index(inplace=True)
mpg[['mean']]

mpg = mpg[['origin','mean','std','count','min','max']]
mpg.insert(3,'sum',seriesSum)
mpg

origin         mean         std     sum  count     min     max
0  europe  2423.300000  490.043191  169631   70.0  1825.0  3820.0
1   japan  2221.227848  320.497248  175477   79.0  1613.0  2930.0
2     usa  3361.931727  794.792506  837121  249.0  1800.0  5140.0